import * as path from "node:path";
import type { AnalysisReport } from "./model";

export function renderMarkdownReport(report: AnalysisReport): string {
  const { stats } = report;
  const lines = [
    "# Exception Lens Boundary Coverage Report",
    "",
    `Generated: ${report.generatedAt}`,
    "",
    "## Summary",
    "",
    "| Metric | Value |",
    "| --- | ---: |",
    `| Boundary coverage | **${stats.coveragePercent}%** |`,
    `| Routes traced | ${stats.routeCount} |`,
    `| Exception paths | ${stats.exceptionPathCount} |`,
    `| Explicitly mapped | ${stats.mappedCount} |`,
    `| Unmapped | ${stats.unmappedCount} |`,
    "",
    "## Routes",
    "",
  ];

  for (const route of report.routes) {
    lines.push(`### ${route.method.toUpperCase()} ${route.path}`, "", `Handler: \`${route.handlerName}\``, "");
    if (!route.exceptions.length) {
      lines.push("No exception paths were discovered.", "");
      continue;
    }
    lines.push("| Exception | Result | Source |", "| --- | --- | --- |");
    for (const occurrence of route.exceptions) {
      const issue = route.issues.some((candidate) => candidate.exception.id === occurrence.id);
      const relativeFile = path.relative(report.workspaceRoot, occurrence.location.file).replaceAll("\\", "/");
      lines.push(`| \`${occurrence.name}\` | ${issue ? "⚠️ Unmapped" : "✅ Mapped"} | \`${relativeFile}:${occurrence.location.line}\` |`);
    }
    lines.push("");
  }

  if (report.mappings.length) {
    lines.push("## Middleware mappings", "", "| Error | HTTP status | Middleware |", "| --- | ---: | --- |");
    for (const mapping of report.mappings) {
      lines.push(`| \`${mapping.errorType}\` | ${mapping.statusCode ?? "unknown"} | \`${mapping.middlewareName}\` |`);
    }
    lines.push("");
  }

  lines.push("---", "Generated by [Exception Lens](https://github.com/JohnJosephTopacio/exception-lens).", "");
  return lines.join("\n");
}
